In [1]:
import numpy as np
import pandas as pd
from scipy.interpolate import griddata

from lets_plot import *

In [2]:
LetsPlot.setup_html()

In [3]:
max_r = 3 # TODO: 100
max_theta = 2.0 * np.pi
number_points = 20 # TODO: 5_000
np.random.seed = 42

In [4]:
grid_r, grid_theta = np.meshgrid(
    np.linspace(0, max_r, 2 * max_r), # r
    np.linspace(0.0, max_theta, max_r) # theta
)

In [5]:
print(grid_r.shape)
grid_r

(3, 6)


array([[0. , 0.6, 1.2, 1.8, 2.4, 3. ],
       [0. , 0.6, 1.2, 1.8, 2.4, 3. ],
       [0. , 0.6, 1.2, 1.8, 2.4, 3. ]])

In [6]:
print(grid_theta.shape)
grid_theta

(3, 6)


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531,
        6.28318531]])

In [7]:
points = np.random.rand(number_points, 2) * [max_r, max_theta]
print(points.shape)
points

(20, 2)


array([[2.00936138e-03, 5.75988696e+00],
       [3.24252390e-01, 2.51278999e+00],
       [2.23164587e-01, 4.19246957e-01],
       [2.64980812e+00, 5.84204253e+00],
       [1.04020277e+00, 3.74536871e+00],
       [4.21012277e-02, 1.20490415e-01],
       [2.04975010e+00, 5.74567583e+00],
       [9.54136861e-01, 4.65960740e+00],
       [3.76398890e-01, 1.55336294e+00],
       [6.97146731e-02, 2.38357141e+00],
       [1.48853576e-01, 2.48176740e+00],
       [1.63503942e+00, 5.95625078e+00],
       [2.55063040e-01, 5.94600681e+00],
       [1.59889662e+00, 1.36935870e+00],
       [1.90968879e+00, 4.89073410e+00],
       [4.86547728e-01, 1.89115157e+00],
       [2.52331068e+00, 1.48878602e+00],
       [2.22260573e+00, 5.04588048e+00],
       [1.67355538e+00, 2.11766499e+00],
       [4.64385204e-01, 1.39464876e+00]])

In [8]:
values = points[:,0] * np.sin(points[:,1])**2 * np.cos(points[:,1])**2
print(values.shape)
values

(20,)


array([3.76493768e-04, 7.33683350e-02, 3.08522819e-02, 3.95008353e-01,
       2.27220796e-01, 5.99482734e-04, 3.96470195e-01, 2.64826591e-03,
       1.14349894e-04, 1.73764696e-02, 3.49151241e-02, 1.51234036e-01,
       2.48603154e-02, 6.14435875e-02, 5.82087360e-02, 4.34636968e-02,
       1.68193628e-02, 2.12641517e-01, 3.30177524e-01, 1.38225990e-02])

In [9]:
data = griddata(points, values, (grid_r, grid_theta), method='cubic',fill_value=0)
print(data.shape)
data

(3, 6)


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.16528837, 0.33531021, 0.30578057, 0.14797681,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [10]:
df = {
    'x': grid_theta.flatten(), 
    'y': grid_r.flatten(), 
    'z': data.flatten()
}

In [11]:
p = ggplot(df) + \
    geom_tile(aes('x', 'y', color='z', fill='z'), size=1, tooltips='none') + \
    scale_brewer(['color', 'fill'], palette='Spectral', direction=-1) + \
    theme(axis_title=element_blank())

gggrid([
    p + coord_cartesian() + ggtitle("Rectangular Heatmap"),
    p + coord_polar() + theme(legend_position='none') + ggtitle("Polar Heatmap"),
])